title: Freedom Day Club
description: Promotion of Digital Freedom Days; organization of Graphics and Compute Freedom Day, Document Freedom Day, Hardware Freedom Day, and Software Freedom Day.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
